apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: gymflow
type: Opaque
stringData:
  POSTGRES_USER: "gymflow_user"
  POSTGRES_PASSWORD: "MonMotDePasseSecret123"
  SECRET_KEY: "django-secret-key-super-secure-123456"