services:
  - type: web
    name: gymflow-backend
    runtime: python
    region: frankfurt
    plan: free
    branch: develop
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
